### ISSUE TITLE
Feature Request: Judges

### ISSUE THREAD

**Issue by danielwdunn** [EMurray16/forecastDCI#1]
Add judges by caption to data and analyses. I can help wrangle the data if you can give me some info on how you sourced the original data.

**Comment by EMurray16** [comment]
Can you be a bit more specific? Would you be looking to add the individual judge as a variable the model uses to make the forecast? Split the caption-level scores into subcaptions and do the modeling that way? Both?

More concretely, what value would this add to the forecast? There are lots of ways to assess/analyze judging and individual judges (something I'm ... reluctantly open to), but I find it unlikely that this would make the forecast either more precise or more accurate. Likewise, there are lots of interesting way to visualize data by judges, but I think that's a separate project (that I'm also open to working on).

**Comment by danielwdunn** [comment]
I'm most interested in using historical data to identify trends with individual judges and how they assess certain corps (or even certain caption heads who have changed corps, if that data is available).

That's probably a separate project, though!

**Comment by EMurray16** [comment]
I'm going to mark this as closed because we agree it is outside the scope of the forecast project.

Send me an email @danielwdunn  if you want to work on a judge-specific project, though. Not sure how much time I'll have to help with analysis, but I should be able to at least throw some data your way.
